<Project>

	<PropertyGroup>
		<Product>DogAppBlazor</Product>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
	</PropertyGroup>

</Project>
